x-php: &php   # template
  build:
    dockerfile: ./php/Dockerfile
    context: .

version: '3'
services:
  nginx:
    build:
      dockerfile: ./nginx/Dockerfile
      context: .
    ports:
      - 8080:80
    depends_on:
      - php1
      - php2
  php1:
    <<: *php
  php2:
    <<: *php
     